name: create-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Existing tag name (e.g., v0.2.1)"
        required: true
        type: string

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create or update GitHub Release for tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
