name: publish-on-file

on:
  push:
    branches: [main]
    paths:
      - ".release/version.txt"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: read_version
        run: |
          ver=$(cat .release/version.txt | tr -d '\n' | tr -d '\r')
          if [ -z "$ver" ]; then echo "version file empty"; exit 1; fi
          echo "version=$ver" >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Prepare tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # remove tag if exists to prevent failures
          git tag -d v${{ steps.read_version.outputs.version }} 2>/dev/null || true
          git push origin :refs/tags/v${{ steps.read_version.outputs.version }} 2>/dev/null || true
          npm version ${{ steps.read_version.outputs.version }} --no-git-tag-version
          git tag v${{ steps.read_version.outputs.version }}
          git push origin refs/tags/v${{ steps.read_version.outputs.version }}
      - run: npm ci || npm i
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GitHub Release with changelog
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.read_version.outputs.version }}
          name: v${{ steps.read_version.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup trigger file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm .release/version.txt
          git commit -m "chore(release): cleanup trigger for v${{ steps.read_version.outputs.version }} [skip ci]"
          git push
