name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 0.2.1)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Prepare version and tag (no main commit)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Safety: if tag exists, remove it locally and remotely
          git tag -d v${{ inputs.version }} 2>/dev/null || true
          git push origin :refs/tags/v${{ inputs.version }} 2>/dev/null || true
          # Update package.json version without creating a commit/tag
          npm version ${{ inputs.version }} --no-git-tag-version
          # Create lightweight tag and push it
          git tag v${{ inputs.version }}
          git push origin refs/tags/v${{ inputs.version }}
      - name: Configure npm auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci || npm i
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create GitHub Release with changelog
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
